name = "ArviZPythonPlots"
uuid = "4a6e88f0-2c8e-11ee-0601-e94153f0eada"
authors = ["Seth Axen <seth@sethaxen.com>"]
version = "0.1.13"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
InferenceObjects = "b5cf5a8d-e756-4ee3-b014-01d49d192c00"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PosteriorStats = "7f36be82-ad55-44ba-a5c0-b8b5480d7aa5"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ArviZExampleData = "0.1.5"
CondaPkg = "0.2"
DimensionalData = "0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29"
InferenceObjects = "0.4.13"
Markdown = "1"
OrderedCollections = "1"
PosteriorStats = "0.3, 0.4"
PythonCall = "0.9"
PythonPlot = "1"
Random = "1"
Reexport = "1"
Tables = "1"
julia = "1.10"

[extras]
ArviZExampleData = "2f96bb34-afd9-46ae-bcd0-9b2d4372fe3c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ArviZExampleData", "Random", "Test"]
