[deps]
ArviZ = "131c737c-5715-5e2e-ad31-c244f01c1dc7"
ArviZExampleData = "2f96bb34-afd9-46ae-bcd0-9b2d4372fe3c"
ArviZPythonPlots = "4a6e88f0-2c8e-11ee-0601-e94153f0eada"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
ArviZExampleData = "0.1.5"
DimensionalData = "0.26"
Distributions = "0.25"
Documenter = "1"
